### ISSUE TITLE
Prefix lenght filter on RTR export

### ISSUE THREAD

**Issue by bofh16** [RIPE-NCC/rpki-validator-3#142]
There are ROAs with length, greater than 25. Usually, such prefixes are not accepted in BGP. Is is possible to introduce a prefix length setting for filtering the router updates?

**Comment by lolepezy** [comment]
Hi, 

No, there's no such setting in the validator and, to be honest, we didn't plan one. Since a while ago (about 3 years) we explicitly allow creation of ROAs with lengths up to 32 and there are some use cases for it. I believe, it's the router's job to filter our VRPs that are two small and don't allow them for the RPKI cache. 

But in case you have some limited amount of these ROAs you can use "ignore filter" feature to exclude them (see https://rpki-validator.ripe.net/filters).
