### ISSUE TITLE
"Unsupported record version Unknown-0.0"

### ISSUE THREAD

**Issue by geeohgeegeeoh** [RIPE-NCC/rpki-validator-3#173]
Debian 9. Java 14.

Error retrieving RRDP repository at https://rrdp.ripe.net/notification.xml: Error downloading 'https://rrdp.ripe.net/notification.xml', cause: failed reading response stream for https://rrdp.ripe.net/notification.xml: javax.net.ssl.SSLHandshakeException: Unrecognized record version (D)TLS-0.0 , plaintext connection?

curl is happy. routinator is happy.

**Comment by geeohgeegeeoh** [comment]
fixed for now by using squid as a proxy.

**Comment by ties** [comment]
This was an issue caused by a new version of the jetty http client introduced by a recent spring boot version.

What version are you running? This issue was present in some of our beta builds but should not happen with the recent rc.

If the SSL errors happen they should be visible in the prometheus metrics (`http://<ip>:<port>/metrics`) as SSLException's.

**Comment by geeohgeegeeoh** [comment]
Beta. I built from src and it went away. Close it!

**Comment by ties** [comment]
Good to hear! Thanks for the quick reply.
