### ISSUE TITLE
Can't Load RTR page http://localhost:8081

### ISSUE THREAD

**Issue by JC-ZI** [RIPE-NCC/rpki-validator-3#186]
Do I need to edit the application.properties of rtr?

I am using CentOS 7 with a proxy server. Would we need to add the proxy command like the Validator as the commands below?

rpki.validator.http.proxy.host=10.10.x.x
rpki.validator.http.proxy.port=3128
rpki.validator.rsync.proxy.host=10.10.x.x
rpki.validator.rsync.proxy.port=3128

**Comment by JC-ZI** [comment]
Hi Support,
is there any update of the question?

**Comment by wibisono** [comment]
Hi JC-ZI,

Sorry for late response, but we don't have a user interface page for the RTR server. On port 8081 for the RTR server  you can  query  clients  (http://localhost:8081/clients) and cache information (http://localhost:8081/cache) as REST end points.

The only user interface page we provide is for the validator which by default is on port 8080 (unless configured otherwise).
