### ISSUE TITLE
Terminating due to java.lang.OutOfMemoryError: Java heap space

### ISSUE THREAD

**Issue by cwiech** [RIPE-NCC/rpki-validator-3#190]
For some reason the validator process is terminating and running out of memory with rpki-validator-3.1-2020.01.13.09.31.26

I have increased the allowed memory to 16G and that didn't made a difference. It seems like something is stuck/corrupted, because once the server gets into this state, it will never start again (I have two servers get in this mode... one in the lab, the other in production). I have upgrade the production system to 3.1-2020.05.08.09.26.49 and it is operation again.

These are the memory values (usually I used 4G/6G and that has been fine), I took the production system up to 16G just to see, this lab box has the following.

jvm.memory.initial=8024m       # -Xms jvm option -> initial memory claimed by the jvm
jvm.memory.maximum=10048m      # -Xmx jvm option -> maximum memory for the jvm

Just wanted to add this ticket just case it is helpful.

May 14 14:46:35 rpkitemplate rpki-validator-3.sh[1438]: 2020-05-14 14:46:35,575          INFO           quartzScheduler_Worker-4                          n.r.r.v.r.RrdpServiceImpl                  Processing deltas failed Error downloading 'https://rpki.cnnic.cn/rrdp/d4427960-abb3-49e4-902c-d815a518b867/deltas/646358.xml', cause: failed reading response stream for https://rpki.cnnic.cn/rrdp/d4427960-abb3-49e4-902c-d815a518b867/deltas/646358.xml: java.util.concurrent.ExecutionException: java.io.EOFException: HttpConnectionOverHTTP@51f58f6f::DecryptedEndPoint@6deaf62f{rpki.cnnic.cn./218.241.105.61:443<->/10.1.38.98:49978,OPEN,fill=-,flush=-,to=7309/0}, cause: java.io.EOFException: HttpConnectionOverHTTP@51f58f6f::DecryptedEndPoint@6deaf62f{rpki.cnnic.cn./218.241.105.61:443<->/10.1.38.98:49978,OPEN,fill=-,flush=-,to=7309/0}, cause: HttpConnectionOverHTTP@51f58f6f::DecryptedEndPoint@6deaf62f{rpki.cnnic.cn./218.241.105.61:443<->/10.1.38.98:49978,OPEN,fill=-,flush=-,to=7309/0}, falling back to snapshot processing.
May 14 14:49:09 rpkitemplate rpki-validator-3.sh[1438]: Terminating due to java.lang.OutOfMemoryError: Java heap space
May 14 14:49:09 rpkitemplate systemd[1]: rpki-validator-server.service: main process exited, code=exited, status=3/NOTIMPLEMENTED
May 14 14:49:09 rpkitemplate systemd[1]: Unit rpki-validator-server.service entered failed state.

**Comment by lolepezy** [comment]
Hi,

1. Just to clarify, are you still experiencing the problem? Does it still run out of memory?
2. You don't need such big values, 2Gb is enough, 3Gb, should be more that enough. It is actually better if you leave more memory to the FS cache, it will speed up IO operations.

**Comment by lolepezy** [comment]
In case you still have the problem, I would recommend to reset it, as described here
https://github.com/RIPE-NCC/rpki-validator-3/wiki/Troubleshooting

**Comment by cwiech** [comment]
That seems to have fixed it.

Is there a reason that system doesn’t clean out stale entries on it own and prevent itself from running out of memory? I could consider adding a cron to occasionally remove the database and restart the validator, but it takes it (didn’t clock it… but atleast an hour+) before it can download data from all registries and will accept connections from from rtr process again. Is there way to restart or speed up the sync process to make this faster, this takes the server offline for a good while.

Thanks for the help on this.

**Comment by lolepezy** [comment]
> Is there a reason that system doesn’t clean out stale entries on it own and prevent itself from running out of memory?

This is exceptional behaviour, normally everything should be cleaned up and memory usage stays constant. We have multiple instances running with 1536mb of heap for months.

Nevertheless, to help with your situation and to help us to diagnose the problem

1) Very long initialisation means that that access to some of the repositories is very slow, like 
https://rrdp.twnic.tw/rrdp/notify.xml or 
https://rpki.cnnic.cn/rrdp/notify.xml
This is partially the problem with these repositories, partially with the validator (we are working on improving this). However, it is only a problem when you delete the database, otherwise restart is pretty quick. And normally you don't have to remove the database.

2) If you are still experiencing the problem, could you change 
logging.level.org.springframework.context.annotation=WARN to
logging.level.org.springframework.context.annotation=INFO
in the /etc/rpki-validator-3/application.properties, restart the validator and send us the log content? I.e. the content of "sudo journalctl rpki-validator-3 > log"

3) One more thing you can do is to help us is to add these command line options to the 
/usr/bin/rpki-validator-3.sh: 

"-XX:+HeapDumpOnOutOfMemoryError -XX:HeapDumpPath=/directory"

In this case, if OutOfMemory happens again, it will dump the memory content to the "/directory" and you can send it us (compressed, or give us access to it, whatever you prefer). It would help to analyse what is happening there.

**Comment by lolepezy** [comment]
Hi,

Just to confirm: are you still experiencing the issues you reported?

**Comment by cwiech** [comment]
It is working fine after removing the old database and letting it rebuild. You can close this case.
