### ISSUE TITLE
1. DNS query from rpki-validator-3 and 2.keeping to upgrade the version

### ISSUE THREAD

**Issue by JC-ZI** [RIPE-NCC/rpki-validator-3#209]
1. 
From the log on our firewall , we found that the rpki-validator-3 is keeping to send DNS request to Internet side.
Would you please confirm is that normal and would you please provide the update port (53?) with the dest ip? 

2.
may we need to keeping to upgrade the version? and would you please advice the procedures? 
Parent Directory
repodata/
rpki-rtr-server-3.1-2020.05.22.11.25.noarch.rpm
rpki-validator-3.1-2020.05.22.11.25.noarch.rpm

Thanks,

**Comment by JC-ZI** [comment]
Hi Support,

Do you have any update?

(1)And could you provivde the upgrade steps? we find that the application files were be replaced as we run the install the version of the software.

(2)
We found that the ROA table content is unstable. How to make sure the data is correct?
There are firewall in front of the validator. would you please  advice the service ports?

Thanks.

**Comment by ties** [comment]
> From the log on our firewall , we found that the rpki-validator-3 is keeping to send DNS request to Internet side.
> Would you please confirm is that normal and would you please provide the update port (53?) with the dest ip?

The validator will do DNS requests for the hostnames of all the hosts referred to in the subject information access attributes of the certificates in the trees. Unfortunately I do not know of an easy way to give a bound on this set.

> (1)And could you provivde the upgrade steps? we find that the application files were be replaced as we run the install the version of the software.

Which files were edited?
We made packaging changes recently. The configuration file that should be edited is the `application.properties`. This is marked as a configuration file/should not be overwritten on updates.

If it does so, please let us know.

> We found that the ROA table content is unstable.
> I compared my validator to the "offical one": https://rpki-validator.ripe.net/trust-anchors
> the content is always different with us.

Because the RPKI is a distributed system there is always some divergence between (instances of) validators. Over time they should be consistent: The same update should arrive at all validators.

As an example, on our testbed I see the following divergence in the number of ROAs seen:
<img width="1690" alt="Screenshot 2020-06-02 at 15 16 49" src="https://user-images.githubusercontent.com/199058/83524751-55f77180-a4e4-11ea-8938-d1a173fc329c.png">


> There are firewall in front of the validator. would you please advice the service ports?

Outgoing: HTTPS on 443, rsync on 873, dns on 53 udp.
There is the option to use a http and rsync proxy.

**Comment by lolepezy** [comment]
> (1)And could you provivde the upgrade steps? we find that the application files were be replaced as we run the install the version of the software.

We have found some potential bugs in the happy eyeballs DNS (RFC8305) implementation and we have release a release candidate. You can try it here:
https://ftp.ripe.net/tools/rpki/validator3/rc/centos7/repo/rpki-validator-3.1-2020.05.28.16.03.06.noarch.rpm
and see if the DNS behaviour has improved. 

To upgrade to the RC version the easiest would be to download the RPM using the link above and install the package using `yum install ./rpki-validator-3.1-2020.05.28.16.03.06.noarch.rpm`.

Alternatively you can configure RC repository in your system as described here
https://github.com/RIPE-NCC/rpki-validator-3/wiki/RIPE-NCC-RPKI-Validator-3-RELEASE-CANDIDATES

Then you can upgrade using the `yum install rpki-validator` command.

**Comment by JC-ZI** [comment]
Hi ties,
Thanks for your support.

**- About the DNS**, we have DNS servers for resolving purposes but we find that the DNS send to Internet direction instead our internal DNS servers surely we have configured DNS setting on OS (CentOS 7) 

or Does the vaildater DNS send request to Internet direction by default?

**- About the software upgrade**. We had to upgrade the validator to the latest version.
Both application.properties have been overwritten on updates and the result is fine with errors.
We just to clone back to the old version. would you please advise or could provide any ref of the upgrade?

Thanks.

**Comment by JC-ZI** [comment]
Thanks lolepezy , will try.

**Comment by lolepezy** [comment]
Hi, we believe the problem with DNS is fixed, so please reopen this issue if you thing it's not.

**Comment by JC-ZI** [comment]
Hi we tried to upgrade the version but there are lot error.
<img width="1211" alt="Screenshot 2020-09-01 at 5 50 22 PM" src="https://user-images.githubusercontent.com/59159878/91835256-bc269880-ec7b-11ea-9382-66a63bd4b44d.png">
