### ISSUE TITLE
Troubleshooting propagation delays

### ISSUE THREAD

**Issue by lukastribus** [RIPE-NCC/rpki-validator-3#264]
Hello,

yesterday we saw a unexpected ROA propagation delay.

After updating a ROA in the RIPE lirportal, NTT, Telia and Cogent saw the update within an hour, but a specific rpki validator 3.1-2020.08.06.14.39 in a third party network did not converge for more than 4 hours.

It was about:
`37.186.128.0/18 origin 20811 maxlength /18`

(and other prefixes with 20811 origin)

maxlength was changed to /24.

According to the [Cloudflare RPKI Dashboard](https://rpki.cloudflare.com/?view=explorer&prefix=37.186.128.0/18), the ROA was emitted at `Sun, 30 Aug 2020 12:17:33 GMT`, while the RIPE rpki-validator-3 in that particular network picked this change up only at ~ 16:50 UTC (+- 15 minutes), more than 4 hours later.

We will try to see if we can reproduce this issue.

Could you help us clarify:

- what are the configuration settings that could impact propagation like this?
- how can we debug this if we reproduce the issue?

Thank you,
Lukas

**Comment by ties** [comment]
Hi,

Unfortunately `3.1-2020.08.06.14.39` sometimes took a very long time to update. This has been fixed in the last release (`3.1-2020.08.20.14.52`) and in the current release candidate. I expect that you hit this delay instead of the configuration of the validator.

The defaults for refreshes are:
  * The `rpki.validator.rsync.repository.download.interval` property, defaulting to ten minutes.
  * The `rpki.validator.rrdp.repository.download.interval` property, defaulting to two minutes.
  * And the rtr server cache is refreshed every minute.

The set of objects is only updated when a trust anchor (with all repositories below it) are in a stable state. It's best if @lolepezy clarifies this.

If you want to debug this the `rpkivalidator_last_validation_run` metric (`/metrics`) is a good start. This contains the last update for a repository. If this is "too long ago" (e.g. `time() - rpkivalidator_last_validation_run` is above some threshold) the validator is not in a healthy state. 

-Ties

**Comment by lukastribus** [comment]
Are you saying that `3.1-2020.08.20.14.52` is the latest stable released version or is it a release candidate? Because the release page on Github here suggests that `3.1-2020.08.06.14.39` is the latest.

Thanks

**Comment by ties** [comment]
`3.1-2020.08.20.14.52` is the latest stable released version. It is in our repositories and is the latest tag on GitHub. I will keep in mind that people use the GitHub releases to track the latest release (I'm not making one right now because we may make another one later this week).

Do you monitor the repository to follow the releases?

**Comment by lukastribus** [comment]
I'm not using RPKI-Validator myself and the network in question already did upgrade to `3.1-2020.08.20.14.52` at this point. I will try some ROA updates and see how this networks reacts in the coming days.

Regarding the release, yes, it's confusing when some github releases have been defined but not for the latest release, because it the end, github then suggests that the latest release is `3.1-2020.08.06.14.39` while it really is `3.1-2020.08.20.14.52`. If people see it at all, they likely think the latter is a RC as opposed to a final stable release.

Also, when using Github's "Releases only" notification features, you do not get updates for git tags. 
3.1-2020.08.06.14.39 on August 6th is the last notification I received from github, because that's about GH releases, not about git tags.

I brought this specific confusion between tags and releases up to GH folks a few years back, because the UI is quite confusing, they are aware ...

But that's off-topic here. I will get back to you in a few days when I was able to send some ROA updates to this network and check with them how fast they update.

**Comment by ties** [comment]
Thanks for the clarification about the Github releases. I see how the tag could be interpreted as an RC. I agree that is confusing and made a not to consistently make them in the future.

Good to hear that the network updated to the latest release. This one should update consistently (but not very fast). We are working on a number of changes that should make validation significantly faster and less memory intensive. We run this on multiple instances that are being monitored and should likely be able to release this in our next sprint (but no guarantees on that timing...).

Please let us know if the ROAs do not propagate as you expect. This whole chain with multiple asynchronous processes (creation, publication, retrieval, processing, update of rtr server, transfer via rtr protocol, router processing) is quite complicated :).

**Comment by lukastribus** [comment]
The validator in question now converges as expected. Thanks for the support!
