### ISSUE TITLE
rpki-validator-3 error after upgrade the version and service is still up/down

### ISSUE THREAD

**Issue by JC-ZI** [RIPE-NCC/rpki-validator-3#267]
1. Could provide the upgrade steps? Seems there is no official steps to users.
And the configuration files have been recovered. We need to edit the files again.

2. There are many object errors:
<img width="1302" alt="Screenshot 2020-09-01 at 6 16 14 PM" src="https://user-images.githubusercontent.com/59159878/91838905-cd25d880-ec80-11ea-8ab1-f43c32199aeb.png">

<img width="1211" alt="Screenshot 2020-09-01 at 5 50 22 PM" src="https://user-images.githubusercontent.com/59159878/91838916-d020c900-ec80-11ea-9227-cb092741cfc4.png">

3. The service is still up / down
<img width="1168" alt="Screenshot 2020-09-01 at 4 28 07 PM" src="https://user-images.githubusercontent.com/59159878/91839108-1a09af00-ec81-11ea-96ad-a00c5094d1dd.png">

4. Please advise how to increase the size of jvm memory heap properly.

**Comment by JC-ZI** [comment]
the problem is insisted even we increased the size: 
jvm.mem.maximum=3072m

<img width="2015" alt="Screenshot 2020-09-02 at 9 47 10 AM" src="https://user-images.githubusercontent.com/59159878/91929133-50dad600-ed10-11ea-8256-113c6727598d.png">
<img width="2019" alt="Screenshot 2020-09-02 at 9 47 16 AM" src="https://user-images.githubusercontent.com/59159878/91929134-520c0300-ed10-11ea-9418-35567c1154c2.png">
<img width="1755" alt="Screenshot 2020-09-02 at 10 58 11 AM" src="https://user-images.githubusercontent.com/59159878/91929144-559f8a00-ed10-11ea-9bbe-2bbe7261f20f.png">

**Comment by JC-ZI** [comment]
dear support,
any update?

**Comment by ties** [comment]
Hi,

First of all: It's best to contact `ncc@ripe.net` for support questions. The issues here are primarily for development. I'm working on another project today but I'll quickly respond to your questions/

#### packaging:
In one of our earlier releases we changed the packaging. The `application-defaults.properties` contains the application defaults and is changed on upgrade. The `application.properties` file is marked as a configuration file in the packages and should not be overwritten.

#### object errors

Since your validator has these object errors _and_ is running out of memory, the best way out is to reset the database.

By default this is in `/var/lib/rpki-validator/db`. Please be aware that you need to re-add the ARIN tal if you were using that (or put it in `/var/lib/rpki-validator/preconfigured-tals`. If you remove all files from the `db` directory, it should start cleanly.

You can adjust the amount of memory by the following settings in `application.properties`:
```
jvm.mem.initial=512m       # -Xms jvm option -> initial memory claimed by the jvm
jvm.mem.maximum=1536m      # -Xmx jvm option -> maximum memory for the jvm
```

I hope this helps,
Ties

**Comment by ties** [comment]
A quick follow-up message: You could also try the release candidate version. Should be faster to update, use much less memory, but we are still investigating it's stability.

If you monitor it using prometheus you can use the following alert to make sure it is updating:
```
  - name: ripe.validator_ta_not_updating
    rules:
    - alert: ValidatorDown
      expr: time() - rpkivalidator_last_validation_run > 1800
      for: 5m
      annotations:
        summary: "Trust anchor {{ $labels.trust_anchor }} has not updated for 30 minutes."
      labels:
        severity: "critical"
```
