### ISSUE TITLE
Don't listen on INADDR_ANY

### ISSUE THREAD

**Issue by job** [RIPE-NCC/rpki-validator-3#33]
Following the countless tragedies of all the daemons that by default listened on all IP addresses (like memcached et al), the default for the RPKI Validator version 3 should not be to listen on the equivalent of `INADDR_ANY`. It should bind to `127.0.0.1` (and perhaps `::1`) and nothing more, unless explicitly configured to do so by the administrator of the software installation.

**Comment by timbru** [comment]
Hi Job,

I will give this a more thorough look on Monday.

Just a quick reply for now: I agree with the spirit, but not all of the implementation. I think it's best to have the 'server.address' only in the initial *local* properties file. That way users can just delete the line to have it listen to all addresses if that is what they want. If the property is present in the default and embedded files, then there will be no way to unset it.

**Comment by job** [comment]
I'll happily admit I am no java expert and wasn't entirely sure what all
files do. Feel free to pick from my proposed pull-request what is needed.
Indeed it should not be such that there is no way to unset it. All I
advocate is that by default, without any additional configuration, the
daemon only listens on 127.0.0.1

**Comment by job** [comment]
Unacceptable.

Docker folks should just update their docker file.

If I find a zero day in the implementation and pervert the validator output
the operator will be toasted.

Docker’s appetite for insecure operations should not negatively affect the
rest of the user base.

Again: see the many many memcached incidents (not just the ddos
amplification but also the confidentially breaches and problems due to
insertion of rogue data).

**Comment by timbru** [comment]
So, I never said this was final. I said I wanted more input :) I agree with the principle, but want to think of the impact as well.

I have sought this input and decided that all things considered I agree that a default secure setting is the way to go. Users will just have to read a bit more if they want things public, but then they will also see the pointers on how to do this securely.

Rather than '127.0.0.1' I want for 'localhost'. It is my hope that this will resolve to whatever localhost happens to be in a docker container as well.
