### ISSUE TITLE
Validator doesn't run stable on CentOS Linux release 7.6.1810

### ISSUE THREAD

**Issue by waehlisch** [RIPE-NCC/rpki-validator-3#71]
I have serious trouble to run rpki-validator-3.0-377. After starting, the Validator terminates after a few minutes.

OS: CentOS Linux release 7.6.1810 (Core)
openjdk version "1.8.0_191"
OpenJDK Runtime Environment (build 1.8.0_191-b12)
OpenJDK 64-Bit Server VM (build 25.191-b12, mixed mode)

More log details:
[log.txt](https://github.com/RIPE-NCC/rpki-validator-3/files/2896761/log.txt)

**Comment by wibisono** [comment]
We suggested that you tried the newly released validator 3.1:

* Docker image: https://hub.docker.com/r/ripencc/rpki-validator-3-docker
* RPM: https://ftp.ripe.net/tools/rpki/validator3/prod/centos7/repo/
* Tarball: https://ftp.ripe.net/tools/rpki/validator3/prod/generic/

Change logs:

* Minimize memory consumption and disk requirement by dropping Hibernate/H2 database, and use 
* Xodus https://github.com/JetBrains/xodus as persistence instead.
* Improve responsiveness, set default RPKI object clean up grace period to 48 hours (used to be 7 days).
* Store all the ignore filters and white lists in a slurm.json file instead of the database, so now the database can be deleted any time without losing any user-configured data.
For migration, the content of the 'db' directory should be remove and export and re-import of SLURM is required.

Hope that you won't face the same issues you had with previous versions.
