### ISSUE TITLE
RPKI Validator Hangs for API calls while performing validation runs

### ISSUE THREAD

**Issue by jof** [RIPE-NCC/rpki-validator-3#89]
Hello RPKI Validator team! Thanks for making a really high-quality and nice validator application.
I've started building some automation to integrate the RPKI Validator into my network, and I'm running into a bit of a surprise with the API responsiveness.

Essentially, I have some monitoring which runs and periodically polls the HTTP API with a 5 second timeout.
What I am observing is some occasional timeouts, which last for about 30 seconds. During this time, the API is totally unresponsive. My JVM seems to accept TCP connections, and queue up requests, but no response data is sent during this 30 second window.

Once I enabled some debug logging and dug a little deeper, what I observed what Quartz kicking off repository validation runs for many of my configured repositories just as the timeouts started happening.
Naïvely, it would seem that several repository validation runs running at the same time are choking up the process and blocking API requests.

I can easily dedicate system resources to this application.
We would like to ensure that the API is nearly-always available during "normal" operation.

Are there maybe some suggested scaling approaches we could try out?
Maybe there is some way in Spring we could have dedicated threadpools for different parts of the application?

For now, I have worked around this by having my API client use some exponential backoff timers and retries to work around these periods of API stalls.

Here is a logging sample from one of these stall periods.
[rpki_stalls.txt](https://github.com/RIPE-NCC/rpki-validator-3/files/3201985/rpki_stalls.txt)
`rpki-validator-3.sh` are the logs from the RPKI Validator 3 application.
`custom_rpki_controller` are the logs from our monitoring application showing the timeouts.

**Comment by lolepezy** [comment]
Hi Jonathan,

The current version of the validator does indeed has the issue you described and unfortunately, there is no easy way to avoid this. These timeouts are caused by the long transaction commits and locks in the underlying H2 database. We are rewriting the storage subsystem so that such issues do not appear again.

There is a branch of the validator, using LMDB instead of H2. It is not officially released, as it has some data integrity issues, but if you feel comfortable digging into the code, you can build the version from lmdb-storage branch. Or you can get it from the release-candidate repository: 
https://ftp.ripe.net/tools/rpki/validator3/rc/centos7/repo/rpki-validator-3.0-423.noarch.rpm
It has much better responsiveness characteristics, so you can do some measurements and conclude if it able do what you want. 

Having said that, we have to move from LMDB to another key-value storage and only after that there will be an official stable release, it will take some time. And we will try to keep the performance characteristics of the LMDB-version.

**Comment by wibisono** [comment]
We finally released version 3.1. Feel free to give it a try:

Docker image: https://hub.docker.com/r/ripencc/rpki-validator-3-docker
RPM: https://ftp.ripe.net/tools/rpki/validator3/prod/centos7/repo/
Tarball: https://ftp.ripe.net/tools/rpki/validator3/prod/generic/

Change logs:

* Minimize memory consumption and disk requirement by dropping Hibernate/H2 database, and use Xodus https://github.com/JetBrains/xodus as persistence instead.
* Improve responsiveness, set default RPKI object clean up grace period to 48 hours (used to be 7 days).
* Store all the ignore filters and white lists in a slurm.json file instead of the database, so now the database can be deleted any time without losing any user-configured data.
* For migration, the content of the 'db' directory should be remove and export and re-import of SLURM is required.
