### ISSUE TITLE
Memory leak on CentOS7 

### ISSUE THREAD

**Issue by zaval1976** [RIPE-NCC/rpki-validator-3#92]
Hello.
I'm trying to launch RPKI in my company. I'm installed RPM -   rpki-rtr-server-3.1-2019.07.23_15.00.28.noarch.rpm and rpki-validator-3.1-2019.07.23_15.00.28.noarch.rpm with Java 8 on СentOS7 under VMWare.
I see the leak of buff/cache memory. Early, I'm added the memory up to 6Gb, but less which 1 day she ended and begin use swap:

[root@rpki001 ~]# cat /proc/meminfo
MemTotal:        5944196 kB
MemFree:          163828 kB
MemAvailable:    2979668 kB
Buffers:             152 kB
Cached:          2999024 kB
SwapCached:           24 kB
Active:          5052700 kB
Inactive:         403208 kB
Active(anon):    2397600 kB
Inactive(anon):    76308 kB
Active(file):    2655100 kB
Inactive(file):   326900 kB
Unevictable:           0 kB
Mlocked:               0 kB
SwapTotal:       2097148 kB
SwapFree:        2096884 kB

**Comment by lolepezy** [comment]
Hi,

The validator uses mmap-ed files for the internal storage, could it be that it distorts your statistics? Also what are the VIRT and RES sizes?

We are running a couple of instances on CentOS 7 VMs as well and in our case VIRT is about 5Gb and RES is 1.9Gb, so your numbers don't look very strange.

There is a way to reduce the RAM and disk (and mmap-ed space) usage by editing /etc/rpki-validator-3/application.properties file.
1) you can reduce jvm.mem.maximum from 1536m to 1024m. It will keep working fine, value 1536m is set "just in case" for some corner cases which normally don't happen.
2) you can change rpki.validator.rpki.object.cleanup.grace.duration from P7D to something like P2D which would result in objects stored in cache for 2 days instead of 7, which makes the whole storage smaller.

Hope that helps.

**Comment by zaval1976** [comment]
Thanks, it got better.
